name: Publish the Editor CellDL as a npm package
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set the timezone to New Zealand
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: 'Pacific/Auckland'

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        # Install the latest version of npm since we need npm 11.5.1 or later to publish to npm using OIDC (see
        # https://docs.npmjs.com/trusted-publishers).
        run: npm install -g npm@latest
      - name: Install bun
        run: npm install -g bun

      - name: Build the CellDL Editor as a component
        run: |
          bun install
          cd src/renderer
          bun build:lib

      - name: Publish the CellDL Editor on npm
        run: |
          cd src/renderer
          npm publish --access public --no-git-checks
